application: widowmaker-invitational
version: 1
runtime: python27
api_version: 1
threadsafe: yes

default_expiration: "5d"

builtins:
- appstats: on
- admin_redirect: on
- deferred: on

libraries:
- name: webapp2
  version: "2.5.2"
- name: ssl
  version: "2.7"

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /(css|font-awesome|fonts|img|js)/(.*)$
  static_files: static/\1/\2
  upload: static/(css|font-awesome|fonts|img|js)/.*$

- url: /
  static_files: static/index.html
  upload: static/index.html

- url: /admin
  static_files: static/admin.html
  upload: static/admin.html

- url: /app/.*
  script: main.app
